
#' Generate a B-Contour Plot
#' 
#' This method can be used for sensitivity models that contain (at least) two
#' comparative bounds and visualizes how the b-factors in the comparative bounds
#' affect the estimated partially identified range (PIR). Users specify a range of values
#' for the two b-factors and the method plots the contour lines for the upper or lower
#' end of the PIR.
#'
#' @param sa An object of the class \code{sensana}.
#' @param pir_lower Logical; if \code{TRUE}, the lower end of the PIR is plotted.
#'   Otherwise, the upper end is plotted.
#' @param bound1 Character. The name of the first comparative bound.
#' @param range1 Numeric vector of length 2 specifying the lower and upper ends
#'   of the range of the first b-factor.
#' @param bound2 Character. The name of the second comparative bound.
#' @param range2 Numeric vector of length 2 specifying the lower and upper ends
#'   of the range of the second b-factor.
#' @param val_interest Numeric; the value of interest for the user; Default is `0`.
#' @param grid_specs_b A named list of the two numeric values \code{N1b} and \code{N2b},
#'   specifying the resolution of the contour plot, i.e. the number of b-factors
#'   for which the PIR is computed.
#' @param grid_specs A named list of the three numeric values `N1`, `N2` and `N5` specifying
#'   the number of points considered in the grid search for each of the three dimensions.
#' @param eps A small numeric number to bound sensitivity parameters away from `1`
#'   and `-1`. Default is \code{0.001}.
#' @param bw Logical; whether to generate a black-and-white plot. Default is \code{FALSE}.
#'
#' @return An object of the class `ggplot` that can be printed.
#'
#'
#' @examples
#' set.seed(123)
#' u <- rnorm(20)
#' xt <- -0.25*u + rnorm(20)
#' xp <- 0.5 * xt + rnorm(20)
#' z <- 0.25 * xt - xp + u + rnorm(20)
#' d <- 0.5 * xt + 0.5 * xp + u + 2*z + rnorm(20)
#' y <- d + 2*xp - xt + z + u + rnorm(20)
#' sa <- sensana(y = y, d = d, x = data.frame(xt = xt, xp = xp), z = z,
#'               dep_x = "xt", indep_x = "xp", alpha = 0.05, quantile = "t")
#'
#' sa <- add_bound(sa, arrow = "UD", kind = "direct", lb = -0.3, ub = 0.3)
#' sa <- add_bound(sa, arrow = "ZY", kind = "direct", lb = -0.3, ub = 0.3)
#' sa <- add_bound(sa, arrow = "UD", kind = "comparative",
#'                 b = 0.2, J = "xp", I = NULL, name = "bud-comp")
#' sa <- add_bound(sa, arrow = "UY", kind = "comparative-d",
#'                 b = 0.3, J = "xp", I = NULL, name = "buy-comp")
#' 
#' pl <- b_contours(sa, pir_lower = TRUE,
#'                  bound1 = "bud-comp", range1 = c(0.05, 0.4),
#'                  bound2 = "buy-comp", range2 = c(0.1, 0.6),
#'                  val_interest = 0)
#' # print(pl)
#'
#' @export
b_contours <- function(sa, pir_lower, bound1, range1, bound2, range2,
                       val_interest = 0, grid_specs_b = list(N1b = 20, N2b = 20),
                       grid_specs = list(N1 = 100, N2 = 100, N5 = 100),
                       eps = 0.001, bw = FALSE) {
  
  if (!is.numeric(val_interest) || length(val_interest) != 1) {
    stop("'val_interest' must be a number.")
  }
  
  if (!any(bw %in% c(TRUE, FALSE))) {
    stop("'bw' must be a boolean value.")
  }

  data <- b_contours_data(sa, pir_lower, bound1, range1, bound2, range2,
                          grid_specs_b, grid_specs, eps)

  xlab <- sa$bounds[bound1, "arrow"]
  ylab <- sa$bounds[bound2, "arrow"]
  b1_sa <- sa$bounds[bound1, "b"]
  b2_sa <- sa$bounds[bound2, "b"]

  b_contours_plot(data, val_interest, pir_lower, b1_sa, b2_sa,
                  range1, range2, xlab, ylab, bw)
}


#' Generate the Data for a B-Contours Plot
#' 
#' If users want to customize the plot generated by [b_contours()], they can use
#' this function to compute the data needed for the contours plot and then proceed
#' to plot it themselves.
#' 
#' @inheritParams b_contours
#' 
#' @return A data frame frame with `N1b * N2b` rows and 3 columns: The columns
#'   `x` and `y` contain the values of the first and second b-factor, respectively.
#'   The column `z` contains the corresponding upper/lower end of the PIR. 
#' 
#' @examples
#' set.seed(123)
#' u <- rnorm(20)
#' xt <- -0.25*u + rnorm(20)
#' xp <- 0.5 * xt + rnorm(20)
#' z <- 0.25 * xt - xp + u + rnorm(20)
#' d <- 0.5 * xt + 0.5 * xp + u + 2*z + rnorm(20)
#' y <- d + 2*xp - xt + z + u + rnorm(20)
#' sa <- sensana(y = y, d = d, x = data.frame(xt = xt, xp = xp), z = z,
#'               dep_x = "xt", indep_x = "xp", alpha = 0.05, quantile = "t")
#'
#' sa <- add_bound(sa, arrow = "UD", kind = "direct", lb = -0.3, ub = 0.3)
#' sa <- add_bound(sa, arrow = "ZY", kind = "direct", lb = -0.3, ub = 0.3)
#' sa <- add_bound(sa, arrow = "UD", kind = "comparative",
#'                 b = 0.2, J = "xp", I = NULL, name = "bud-comp")
#' sa <- add_bound(sa, arrow = "UY", kind = "comparative-d",
#'                 b = 0.3, J = "xp", I = NULL, name = "buy-comp")
#' 
#' df <- b_contours_data(sa, pir_lower = TRUE,
#'                       bound1 = "bud-comp", range1 = c(0.05, 0.4),
#'                       bound2 = "buy-comp", range2 = c(0.1, 0.6),
#'                       grid_specs_b = list(N1b = 20, N2b = 20),
#'                       grid_specs = list(N1 = 100, N2 = 100, N5 = 100),
#'                       eps = 0.001)
#'                       
#' # proceed to plot the data in df
#' 
#' @export
b_contours_data <- function(sa, pir_lower, bound1, range1, bound2, range2,
                            grid_specs_b, grid_specs, eps = 0.001){
  
  check_b_contours_data(sa, pir_lower, bound1, range1, bound2, range2,
                        grid_specs_b, grid_specs, eps)

  b1_seq <- seq(range1[1], range1[2], length = grid_specs_b$N1b)
  b2_seq <- seq(range2[1], range2[2], length = grid_specs_b$N2b)

  data_mat <- cbind(sa$y, sa$d, sa$z, sa$xp, sa$xt)
  if (is.null(sa$z)) {
    colnames(data_mat)[c(1,2)] <- c("y", "d")
  } else {
    colnames(data_mat)[c(1,2,3)] <- c("y", "d", "z")
  }
  indices <- 1:length(sa$y)
  indep_x <- if (is.null(sa$xp)) NULL else colnames(sa$xp)
  dep_x <- if (is.null(sa$xt)) NULL else colnames(sa$xt)

  pir_b1b2 <- function(b1, b2) {
    bounds_b1b2 <- sa$bounds
    bounds_b1b2[bound1, "b"] <- b1
    bounds_b1b2[bound2, "b"] <- b2
    
    pir <- one_opt(data_mat, indices, bounds_b1b2, grid_specs, indep_x, dep_x, eps)
    if (pir_lower) pir[1] else pir[2]
  }

  pir_val <- outer(b1_seq, b2_seq, Vectorize(pir_b1b2))

  cbind(expand.grid(x = b1_seq, y = b2_seq), z = as.vector(pir_val))
}






#' @importFrom rlang .data
b_contours_plot <- function(data, val_interest, pir_lower,
                            b1_sa, b2_sa, range1, range2,
                            xlab, ylab, bw) {

  title <- "b-sensitivity contours: "
  title <- if (pir_lower) paste0(title, "lower point PIR") else paste0(title, "upper point PIR")

  text_point <- paste0("(", b1_sa, ", ", b2_sa, ")")

  make_breaks <- function(range, binwidth) {
    signif(pretty(range, 15), 4)
  }
  make_breaks_ex <- function(range, binwidth) {
    b <- make_breaks(range, binwidth)
    b[b != val_interest]
  }

  pl <- ggplot2::ggplot(data, ggplot2::aes(x = .data$x, y = .data$y, na.rm = TRUE)) +
    metR::geom_contour_fill(ggplot2::aes(z = .data$z,
                                         fill = ggplot2::after_stat(.data$level)),
                            breaks = make_breaks,
                            show.legend = FALSE) +
    metR::geom_contour2(ggplot2::aes(z = .data$z,
                            label = ggplot2::after_stat(.data$level)),
                        breaks = make_breaks_ex,
                        col = "black",
                        label_size = 3,
                        size = 0.1) +
    metR::geom_contour2(ggplot2::aes(z = .data$z,
                                     label = ggplot2::after_stat(.data$level)),
                        breaks = val_interest,
                        linewidth = 0.8,
                        col = "black")
  
  if (bw) {
    pl <- pl + metR::scale_fill_discretised(low = "#5A5A5A", high = "#F5F5F5")
  } else {
    pl <- pl + metR::scale_fill_divergent_discretised(midpoint = val_interest)
  }
  
  pl <- pl +
    ggplot2::geom_point(data = data.frame(x = b1_sa,
                                          y = b2_sa),
                        mapping = ggplot2::aes(x = .data$x, y = .data$y),
                        col = "black") +
    ggrepel::geom_text_repel(data = data.frame(x = b1_sa,
                                               y = b2_sa,
                                               label = text_point),
                             mapping = ggplot2::aes(x = .data$x,
                                                    y = .data$y,
                                                    label = .data$label),
                             col = "black",
                             size = 3.5,
                             xlim = range1,
                             ylim = range2) +
    ggplot2::labs(x = xlab, y = ylab, title = title) +
    ggplot2::theme_bw() +
    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5),
                   axis.text = ggplot2::element_text(size = 11),
                   axis.title = ggplot2::element_text(size = 13),
                   title = ggplot2::element_text(size = 12))
  pl
}
