# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grid_search <- function(N1, N2, N5, full_grid, lb_p1s, ub_p1s, lb_p2s, ub_p2s, lb_p3s, ub_p3s, lb_p6s, ub_p6s, lb_p7s, ub_p7s, lb_p4, ub_p4, exist_comp_uy_bound, exist_tsls_bound, c1, c2, c3, c4, c5, c6, c7, b7) {
    .Call(`_optsens_grid_search`, N1, N2, N5, full_grid, lb_p1s, ub_p1s, lb_p2s, ub_p2s, lb_p3s, ub_p3s, lb_p6s, ub_p6s, lb_p7s, ub_p7s, lb_p4, ub_p4, exist_comp_uy_bound, exist_tsls_bound, c1, c2, c3, c4, c5, c6, c7, b7)
}

resid_cpp <- function(X, Y) {
    .Call(`_optsens_resid_cpp`, X, Y)
}

r_marginal <- function(A, B) {
    .Call(`_optsens_r_marginal`, A, B)
}

r_partial <- function(A, B, C) {
    .Call(`_optsens_r_partial`, A, B, C)
}

r2_marginal <- function(A, B) {
    .Call(`_optsens_r2_marginal`, A, B)
}

r2_partial <- function(A, B, C) {
    .Call(`_optsens_r2_partial`, A, B, C)
}

